<?php

namespace mPhpMaster\MigrationSnapshot;

final class EventServiceProvider extends \Illuminate\Foundation\Support\Providers\EventServiceProvider
{
//    protected $listen = [
        // CONSIDER: Only registering these when Laravel version doesn't have
        // more specific hooks.
//        'Illuminate\Console\Events\CommandFinished' => ['mPhpMaster\MigrationSnapshot\Handlers\MigrateFinishedHandler'],
//        'Illuminate\Console\Events\CommandStarting' => ['mPhpMaster\MigrationSnapshot\Handlers\MigrateStartingHandler'],
//    ];

    public function boot()
    {
        if(config('migration-snapshot.register_starting_handler', false)) {
            $this->listen['Illuminate\Console\Events\CommandStarting'] = ($this->listen['Illuminate\Console\Events\CommandStarting'] ?? []) + ['mPhpMaster\MigrationSnapshot\Handlers\MigrateStartingHandler'];
        }

        if(config('migration-snapshot.register_finished_handler', false)) {
            $this->listen['Illuminate\Console\Events\CommandFinished'] = ($this->listen['Illuminate\Console\Events\CommandFinished'] ?? []) + ['mPhpMaster\MigrationSnapshot\Handlers\MigrateFinishedHandler'];
        }

        parent::boot(); // TODO: Change the autogenerated stub
    }
}
